### ISSUE TITLE
How can I build this/how can I recrate this?

### ISSUE THREAD

**Issue by TechStudent10** [Abb1x/pythonOS#2]
Similar to https://github.com/Abb1x/snek/issues/2

**Comment by TechStudent10** [comment]
Update: So I figured it out.

1. You need Linux. There is no escaping Linux when creating OSes.
2. You'll need Python 3.10. Here's a guide on how to upgrade: https://python.plainenglish.io/a-guide-to-upgrade-your-python-to-3-10-c0cb82ba662d
3. You'll also need to install `qemu`. So run these two commands.
```bash
sudo apt install qemu
sudo apt install qemu-system-x86-64
```
4. You'll need to do some refactoring.
    1. In `build.py`, wherever you are executing a Python file, change `python` to `python3.10`.
    2. Change line `os.system("./scripts/make_image.py")` to `os.system("python3.10 ./scripts/make_image.py")`.
    3. I am not sure about the rest. If you have problems, let me know here.
5. Run `python3.10 build.py` and you should have a `.iso` file and QEMU should open. You then need to press enter on your keyboard for it to load.

**Comment by llamaking136** [comment]
Yes, Linux is very good for developing operating systems. But, there are ways to counter *only* using Linux. `brew` is a good package manager that does include `qemu` and Python 3.10 for macOS. I'm not sure about Windows, but I'm definitely sure there's software for it.

**Comment by TechStudent10** [comment]
On Windows I'm just using WSL with Ubuntu.

**Comment by TechStudent10** [comment]
Closing in favor of https://github.com/Abb1x/snek/issues/2
